# Generated by Django 3.2.4 on 2022-11-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.TimeField(null=True),
        ),
    ]
