# Generated by Django 3.2.4 on 2022-11-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0002_alter_movie_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='character_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='number_of_lines',
            field=models.IntegerField(null=True),
        ),
    ]
