# Generated by Django 3.2.4 on 2022-11-09 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='posts',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.user'),
        ),
    ]
