# Generated by Django 3.2.4 on 2022-11-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0002_alter_fooditem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfooditem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodDelivery.order'),
        ),
    ]
