# Generated by Django 3.2.4 on 2022-11-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0006_auto_20221109_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfooditem',
            name='food_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_food_items', to='foodDelivery.fooditem'),
        ),
        migrations.AlterField(
            model_name='orderfooditem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_food_items', to='foodDelivery.order'),
        ),
    ]
