# Generated by Django 3.2.4 on 2022-11-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0007_auto_20221109_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='item',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
