# Generated by Django 3.2.4 on 2022-11-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0008_fooditem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='order',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='order',
            field=models.ManyToManyField(related_name='food_items', through='foodDelivery.OrderFoodItem', to='foodDelivery.Order'),
        ),
    ]
