# Generated by Django 3.2.4 on 2022-11-09 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_shop_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reviews',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='reviewed_products',
            new_name='reviewed_product',
        ),
    ]
